### ISSUE TITLE
The download link for the KittiCaltech Pedestrian dataset is no longer accessible.

### ISSUE THREAD

**Issue by vaynelau** [chengtan9907/SimVPv2#10]
The download link for the [KittiCaltech Pedestrian](https://dl.acm.org/doi/10.1177/0278364913491297)  dataset is no longer accessible. Could you please provide a new download link?

**Comment by chengtan9907** [comment]
I found this link is still available for me: https://figshare.com/articles/dataset/KITTI_hkl_files/7985684.  Would you mind trying it again?

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
