### ISSUE TITLE
代码中MIM模型问题

### ISSUE THREAD

**Issue by ShidongC** [chengtan9907/SimVPv2#11]
谢谢你的代码，你的代码对我跑baseline有很大的帮助，用你的代码的时候我遇到了一个问题，对于MIM模型，我将train.py训练1次验证1次改成了训练1次验证4次，这4次验证结果却不同，按我的理解输入数据一样这4次验证结果应该相同

**Comment by chengtan9907** [comment]
感谢您的关注！您的问题似乎不是很清晰，请问能否提供完整的阐述？

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
