### ISSUE TITLE
Question about KittiCaltech bechmark.

### ISSUE THREAD

**Issue by OliviaWang123456** [chengtan9907/SimVPv2#12]
Hi, thank u for releasing the code.
But I encountered some problems while training and evaluating on KittiCaltech benchmark.
In Table 2 of the paper, it writes there are 2042 training samples and 1983 test samples.
But I got 3738 training samples (from Kitti train split)  and I don't know which split of CalTech Pedestrian is used as test samples.

Could you plz tell me the details about KittiCaltech benchmark.
Thanks a lot.

**Comment by vaynelau** [comment]
I have the same questions, too. It will be helpful if the authors could provide the download link of  the CalTech Pedestrian dataset for testing. Thanks.

**Comment by Lupin1998** [comment]
Hi, guys, @OliviaWang123456, @vaynelau. Thanks for your question. For supported datasets, we have provided the links to the paper and download pages in [README](https://github.com/chengtan9907/SimVPv2/blob/master/README.md). Unfortunately, the linked version of the CalTech Pedestrian dataset might have some bugs. You can download the datasets we used from [**Baidu Cloud**](https://pan.baidu.com/s/1fudsBHyrf3nbt-7d42YWWg?pwd=kjfk) (kjfk). Please do not distribute the datasets and only use them for research.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
