### ISSUE TITLE
Is it necessary for the number of input and output frames to be the same?

### ISSUE THREAD

**Issue by 1229308805** [chengtan9907/SimVPv2#13]
Thank you for doing such a wonderful job. I have a question: Does the predicted length of the SIMVP model need to be the same as the input length, or can they be different? For example, can we input 12 frames from the past and predict 4 frames in the future?

**Comment by chengtan9907** [comment]
No, we have provided an implementation for flexible lengths. You can simply change the parameter `pre_seq_length` and `aft_seq_length` to make it.

**Comment by 1229308805** [comment]
Thank you for your response, but I did not see any content related to the parameters pre_seq_length and aft_seq_length in the SimVP_Model class. It seems that the number of input and output frames are equal to the T dimension in the "in_shape" variable. I tried modifying these two parameters in the parser, but it didn't have any effect according to the log.

**Comment by chengtan9907** [comment]
The model is not changed by these two parameters. You can refer to lines 28-49, at https://github.com/chengtan9907/SimVPv2/blob/master/simvp/methods/simvp.py.
