### ISSUE TITLE
Question regarding visualization

### ISSUE THREAD

**Issue by oooolga** [chengtan9907/SimVPv2#14]
Dear Authors,

The pixel values of the experiments typically are normalized to a range (i.e. [0-1]). Is there any reason you use a regular 2D convolution layer without activation (such as sigmod/tanh layers that would normalize the values to such a range) as the last decoder's layer?

On the other hand, how do you normalize the output values for visualization? Do you clip them, or do you do it by another method?

Thanks!

**Comment by chengtan9907** [comment]
We found that using activation functions has little effect on performance. Thus we did not use them. For visualization, we clip the output values, see https://github.com/chengtan9907/SimVPv2/blob/70f593edf761732742474d4627b3e30df1de0251/simvp/core/metrics.py#L73.

**Comment by oooolga** [comment]
Thanks.
