### ISSUE TITLE
TaxiBJ - Question

### ISSUE THREAD

**Issue by Mareeta26** [chengtan9907/SimVPv2#4]
Hi,
I would like to know why PSNR was not used to evaluate the TaxiBJ performance?

Thanks,
Mareeta

**Comment by gaozhangyang** [comment]
Baseline methods do not use this metric. We did not reproduce all baselines  when we wrote the paper, so we did not evaluate PSNR on the TaxiBJ dataset.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
