### ISSUE TITLE
codes for model zoo

### ISSUE THREAD

**Issue by zzzzzx-1115** [chengtan9907/SimVPv2#6]
Thanks for your contributory works! I notice that you have provided experiment resualts of  a lot of models on various datasets. However, codes of some methods are not provided officially (e.g. ConvLSTM), so I wonder whether you implement them yourselves or not? If so, would you mind uploading those codes? If not, I think just a link will also be quite helpful.  Thank you!

**Comment by gaozhangyang** [comment]
At the time of writing the paper we did not reproduce all baseline methods. Now we have implemented the code for many  important work and uploaded the codes.

**Comment by zzzzzx-1115** [comment]
Those codes benefit me a lot. Thank you.
