### ISSUE TITLE
Hyper-parameter settings for mmnist

### ISSUE THREAD

**Issue by oooolga** [chengtan9907/SimVPv2#7]
Thank you for releasing the code!

We have tried to train the SimVP model with your default setting. The results we got could be more optimal. This is the line of code that we've run
`python tools/non_dist_train.py -d mmnist -m SimVP --model_type gsta --lr 1e-3 --ex_name mmnist_simvp_gsta --epoch 600`

The MSE score on the testing set is 47.128. Can you check if there is anything wrong with our settings? And is there a better hyperparameter setting we should use to generate your paper's results?

**Comment by chengtan9907** [comment]
I'm sorry for the misunderstanding. We need the config file to specify the hyperparameters of the model. I suggest you to

**Comment by chengtan9907** [comment]
I'm sorry for the misunderstanding. If the config file is not specified, the code will use the default hyperparameters in `simvp/utils/parser.py`.   To reproduce the experiments in our paper, I suggest you specify the config file:
```
python tools/non_dist_train.py -d mmnist --lr 1e-3 -c ./configs/mmnist/simvp/SimVP_gSTA.py --ex_name mmnist_simvp_gsta
```
We have updated the readme and hope this will help you.

**Comment by oooolga** [comment]
Thanks for the swift reply!
