### ISSUE TITLE
taxibj model results implementation

### ISSUE THREAD

**Issue by MSrobt** [chengtan9907/SimVPv2#9]
Thank you for sharing the code
  I was trying to reproduce the results of the SimVP model in taxibj and I found that I needed to make minor changes to the code in 'config_utils.py' to start training the model.

`temp_config_file = tempfile.NamedTemporaryFile( dir=temp_config_dir, suffix=fileExtname,delete=False)`
  I don't know if this has affected my recurrence results.I tried to reproduce the taxibj dataset using code similar to the mmnist example program.taxibj training time set to 50.

`python tools/non_dist_train.py -d taxibj -c ./configs/taxibj/simvp/SimVP_gSTA.py --ex_name taxibj_simvp_gsta`
 The result of the replication is - mse:0.41158363223075867.Can you check if there is anything wrong with our settings?

**Comment by chengtan9907** [comment]
I'm not quite sure about your issue. I would like to suggest you check the log file to see if the parameters are consistent with those in `configs/taxibj/simvp/SimVP_gSTA.py`.

**Comment by MSrobt** [comment]
Thank you for your reply.
  I checked whether the parameters in the log match the `/configs/taxibj/simvp/SimVP_gSTA.py`，retrained the model using a new example program and uploaded the training log。
`python tools/non_dist_train.py -d taxibj --lr 5e-4 -c ./configs/taxibj/simvp/SimVP_gSTA.py --ex_name taxibj_simvp_gsta`
  I'm not sure if some minor error affected the training results。
[新建文本文档.txt](https://github.com/chengtan9907/SimVPv2/files/10998990/default.txt)

**Comment by chengtan9907** [comment]
It seems that it is a problem with the learning rate. Could you try other learning rates?

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
